### ISSUE TITLE
Does not seem to be working for me

### ISSUE THREAD

**Issue by jpeirce** [eatonphil/linode-deploy-experimental#12]
It creates the linode fine, but then:
/home/jackson/.local/bin> ./linode_deploy_experimental freebsd-11-0    
Fetched all datacenters
Fetched all distributions
Fetched all plans
Created a linode
Waiting for Linode to be created
Added private IP
Created first disk
Created second disk
Waiting for disks to be created
Waiting for disks to be created
Waiting for disks to be created
Disk created
Waiting for disks to be created
Disk created
Created install config
Created normal config
Waiting for Linode to boot into install config
Waiting for Linode to boot into install config
Waiting for ssh server to start
Fetched ips
Started image deploy process
Oh know! An exception!
Traceback (most recent call last):
File "./linode_deploy_experimental", line 9, in <module>
load_entry_point('linode-deploy-experimental==0.1', 'console_scripts', 'linode_deploy_experimental')()
File "/home/jackson/.local/lib/python3.5/site-packages/linode_deploy_experimental/__main__.py", line 199, in main
raise e
File "/home/jackson/.local/lib/python3.5/site-packages/linode_deploy_experimental/__main__.py", line 166, in main
wait_for_ssh(ip.ipaddress, tmp_password, cmd)
File "/home/jackson/.local/lib/python3.5/site-packages/linode_deploy_experimental/__main__.py", line 37, in wait_for_ssh
while subprocess.call([tcl_path, address, password, cmd]) > 0:
File "/usr/lib64/python3.5/subprocess.py", line 247, in call
with Popen(*popenargs, **kwargs) as p:
File "/usr/lib64/python3.5/subprocess.py", line 676, in __init__
restore_signals, start_new_session)
File "/usr/lib64/python3.5/subprocess.py", line 1282, in _execute_child
raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jackson/.local/lib/python3.5/site-packages/linode_deploy_experimental/ssh.tcl'

Doesn't matter if what image I select, they all fail the same way.
If I load a glish console, on boot it shows a PXE message, then a GRUB error "error variable prefix is not set", then boots to a Debian text login.

**Comment by jpeirce** [comment]
I needed to install the package 'expect' on Fedora 25, now it's working, you can close this.

**Comment by eatonphil** [comment]
@jpeirce thanks for taking a look at that. I'll add a note to the README.md about the `expect` dependency.
